CommodityTracker/urls.py
from django.conf.urls import include, url

from . import views

# Home Page
urlpatterns = [
    url(r'^$', views.CommodityHome.as_view(), name='commodity-analytics-home'),
]

# Base Commodities
urlpatterns += [
    url(r'categories/$', views.CategoryListView.as_view(), name='category-list'),
    url(r'category/(?P<pk>\d+)$', views.CategoryDetailView.as_view(), name='category-detail'),
    url(r'base_commodities/$', views.BaseCommodityListView.as_view(), name='base-commodity-list'),
    url(r'base_commodity/(?P<pk>\d+)$', views.BaseCommodityDetailView.as_view(), name='base-commodity-detail'),
]

# Purchase Commodities
urlpatterns += [
    url(r'purchase_commodities/$', views.PurchaseCommodityListView.as_view(), name='purchase-commodity-list'),
    url(r'purchase_commodity/(?P<pk>\d+)$', views.PurchaseCommodityDetailView.as_view(), name='purchase-commodity-detail'),
    url(r'^purchase_commodity_create/$', views.PurchaseCommodityCreate.as_view(), name='purchase-commodity-add'),
]

# Admin Functions
urlpatterns += [
    url(r'^init/$', views.app_init, name='app-init'),
]

boards/urls.py
from django.conf.urls import include, url

from boards import views

urlpatterns = [
    url(r'^$', views.BoardListView.as_view(), name='boards-index'),
    url(r'^boards/(?P<pk>\d+)/$', views.TopicListView.as_view(), name='board_topics'),
    url(r'^boards/(?P<pk>\d+)/new/$', views.new_topic, name='new_topic'),    
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/$', views.PostListView.as_view(), name='topic_posts'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/reply/$', views.reply_topic, name='reply_topic'),
    url(r'^boards/new_post/$', views.NewPostView.as_view(), name='new_post'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/posts/(?P<post_pk>\d+)/edit/$',
    views.PostUpdateView.as_view(), name='edit_post'),
]

webanalytics/urls.py
from django.conf.urls import include, url
from webanalytics import views


urlpatterns = [
    url(r'^$', views.WebAnalyticsHome, name='web-analytics-home'),
    url(r'^viz$', views.VizHome, name='viz-home'),
]

yamaki/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView

from idealytix import views as idealytix_views
from accounts import views as accounts_views
from salesanalytics import views as salesanalytics_views
from webanalytics import views as webanalytics_views
from customeranalytics import views as customeranalytics_views
from inventoryanalytics import views as inventoryanalytics_views
from accountsanalytics import views as accountsanalytics_views
from CommodityTracker import views as purchaseanalytics_views
from boards import views as boards_views
from hranalytics import views as hr_views

#URL pattern mappings

urlpatterns = [
    url(r'^$', idealytix_views.home, name='home'),
]

urlpatterns += [
    url(r'^bakery/', include('idealytix.urls')),
    url(r'^sales/', include('salesanalytics.urls')),
    url(r'^web/', include('webanalytics.urls')),
    url(r'^customer/', include('customeranalytics.urls')),
    url(r'^inventory/', include('inventoryanalytics.urls')),
    url(r'^commodity/', include('CommodityTracker.urls')),
    url(r'^sales/', include('accountsanalytics.urls')),
    url(r'^hr/', include('hranalytics.urls')),
    url(r'^accounts/', include('accounts.urls')),    
    url(r'^forums/', include('boards.urls')),    
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += [
    url(r'^admin/', admin.site.urls),
]

CommodityTracker/models.py
from django.db import models
import json
import quandl
import pandas as pd
from datetime import datetime
from datetime import date
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse


class Category (models.Model):
    name = models.CharField(max_length=25)
    description = models.TextField(max_length=1000, null = False)

    def get_commodity_count(self):
        count = self.basecommodities.count()
        return count

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category-detail', args=[str(self.id)])        

class BaseCommodity(models.Model):
    name = models.CharField(max_length=25, null=False)
    description = models.TextField(max_length=1000, null = False)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='basecommodities')

    # API Details
    api_source = models.CharField(max_length=50)
    api_key = models.CharField(max_length=25)
    api_version = models.CharField(max_length=25, blank=True)
    api_code = models.CharField(max_length=20)

    #
    last_updated = models.DateTimeField(default=date(2000, 1, 1))

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('base-commodity-detail', args=[str(self.id)])      

    def needs_update(self):
        time_since_last_update = date.today() - self.last_updated.date()
        if time_since_last_update.days > 5 :
            print ('commodity data needs update')
            return True
        else:
            print ('commodity data does not need update')
            return False

    def update_data(self):
        if (self.api_source == 'Quandl'):
            quandl.ApiConfig.api_key = self.api_key
            dfset = quandl.Dataset(self.api_code, start_date=str(self.last_updated), end_date=str(date.today()))
            data = dfset.data()
            entries = data.to_pandas()

            print ('INSIDE UPDATE DATA')
#            print ('ENTRIES>>>>>>>>>>')
#            print (entries)

            try:
                for index, row in entries.iterrows():
                    ts = BaseCommodityRecords()
                    ts.base_commodity = self
                    ts.date = index
                    ts.value = row['Value']
                    ts.save()
#                    print (ts)
            except Exception as e:
                print ("Error in making TimeSeries entry:")
                print (e) 

            self.last_updated = date.today()
            return True # Updated

        return False # Not updated
  

# Purchase Commodity
class PurchaseCommodity(models.Model):
    name = models.CharField(max_length=25, null=False)
    description = models.TextField(max_length=1000, null = False)
    company_name = models.CharField(max_length=50)
    #
    last_updated = models.DateTimeField()

    # Benchmark Information
    weight1 = models.FloatField(null=True, default=0, validators=[MinValueValidator(0), MaxValueValidator(100)]) # values between 0 to 1
    weight2 = models.FloatField(null=True, default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])
    weight3 = models.FloatField(null=True, default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])
    benchmark1 = models.ForeignKey(BaseCommodity, on_delete=models.SET_NULL, null=True, related_name='benchmark_1')
    benchmark2 = models.ForeignKey(BaseCommodity, on_delete=models.SET_NULL, null=True, related_name='benchmark_2')
    benchmark3 = models.ForeignKey(BaseCommodity, on_delete=models.SET_NULL, null=True, related_name='benchmark_3')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('purchase-commodity-detail', args=[str(self.id)])      

    def update_values(self, date, value):
        #print ('data types: date: {}, value: {}'.format(type(date), type(value)))
        ts, exists = PurchaseCommodityRecords.objects.get_or_create(
                                                    purchase_commodity = self,
                                                    date = date,
                                                    value = value
        )
        if exists:
            print ('record already existing')
        else:
            print ('new record created') 



# Data Records
class CommodityRecords(models.Model):
    date = models.DateTimeField()
    value = models.FloatField()


# Data Records
class BaseCommodityRecords(CommodityRecords):
    base_commodity = models.ForeignKey(BaseCommodity, on_delete=models.SET_NULL, 
                                        null=True, related_name='records'
                                        )
   

# Data Records
class PurchaseCommodityRecords(CommodityRecords):
    purchase_commodity = models.ForeignKey(PurchaseCommodity, on_delete=models.SET_NULL, 
                                            null=True, related_name='records'
                                        )
 

CommodityTracker/forms.py
from django import forms
from django.forms import ModelForm
from CommodityTracker.models import PurchaseCommodity 
from django.utils.translation import gettext_lazy as _

def myvalidate(value):
    print ('###############inside myvalidate function')
    print (value.file)
    # Do something here

        
class PurchaseCommodityForm(forms.ModelForm):

    commodity_purchase_data  = forms.FileField(help_text = 'Upload csv file ', validators=[myvalidate],)
    class Meta:
        model = PurchaseCommodity
        fields = ('company_name', 
                    'name', 
                    'description', 
                    'benchmark1', 
                    'weight1', 
                    'benchmark2', 
                    'weight2', 
                    'benchmark3', 
                    'weight3' 
        )

        labels = {
            'company_name': _('Enter Company Name'),
        }

        help_texts = {
            'company_name': _('Write Your Company Name.'),
        }

    def clean(self):
        cleaned_data = super().clean()
        print ('###############inside clean function')
        

webanalytics/views.py
from django.shortcuts import render

# Create your views here.

def WebAnalyticsHome(request):

    context = {
        'host_url' : 'http%3A%2F%2Fdashboards.biznessanalytics.com%2F',
        'value' : 'GoogleAnalyticsDashboardBeta&#47;GooogleAnalyticsIntegrationDemo',
        'site_root' : '&#47;t&#47;Misterbaker',
        'name' : 'GoogleAnalyticsDashboardBeta&#47;GooogleAnalyticsIntegrationDemo',
        'embed_code_version' : '2',
    }    
    return render( request, 'webanalytics/home.html', context)


def VizHome(request):

    context = {
        'value' : 'http%3A%2F%2Fdashboards.biznessanalytics.com%2F',
        'width' : '100%',
        'height' : '100%', 
        'host_url' : 'http%3A%2F%2Fdashboards.biznessanalytics.com%2F',
        'embed_code_version' : '2',
        'site_root' : '&#47;t&#47;Misterbaker',
        'name' : 'SalesDashboards_Beta&#47;Home',
        'tabs' : 'yes',
        'toolbar' :'yes',
        'showAppBanner' :'false',
        'showShareOptions' : 'true',
    }    

    return render( request, 'viz.html', context)

CommodityTracker/templates/CommodityTracker/basecommodity_detail.html
{% extends "base_template.html" %}
{% load widget_tweaks %}

{% block title %}
   {{block.super}}: Categories List
{% endblock title %}



{% block content %}

    <h3>Title: {{ basecommodity }}</h3>

    <p><strong>commodity:</strong> {{ basecommodity }}</p> <!-- author detail link not yet defined -->


    <div class="card mb-2" style="box-shadow: 10px 10px lightgrey">
        <div class="card-body p-3">
          <div class="row mb-3">
            <div class="col-10">
                <H3>Historical Price Evolution</H3>
                <div style="height: 450px" id="chart_div_json"></div>
            </div>
            <div class="col-2 text-right">
              <small class="text-muted">some text</small>
            </div>
          </div>
        </div>
      </div>
  

      <div class="card mb-2" style="box-shadow: 10px 10px lightgrey">
          <div class="card-body p-3">
            <div class="row mb-3">
              <div class="col-10" >
                  <H3>Price Table</H3>
                  <div id="table_div_json" ></div>
              </div>
              <div class="col-2 text-right">
                <small class="text-muted">some text</small>
              </div>
            </div>
          </div>
        </div>
    


{% endblock %}


{% block footer %}
<h2> Category Footer </h2>
{{block.super}}
{% endblock footer %}


{% block javascript %} 
<script src="http://www.google.com/jsapi" type="text/javascript"></script>

<script>
        google.load("visualization", "1", {packages:["table", "corechart"]});
        google.setOnLoadCallback(drawTable);
        function drawTable() {

        var json_table_my = new google.visualization.Table(document.getElementById('table_div_json'));
        var json_data_my = new google.visualization.DataTable({{dataset|safe}});
        json_table_my.draw(json_data_my, {showRowNumber: true});


        var json_table_my2 = new google.visualization.LineChart(document.getElementById('chart_div_json'));
        var json_data_my2 = new google.visualization.DataTable({{dataset|safe}});
        json_table_my2.draw(json_data_my2, {showRowNumber: true});
        }
</script>
{% endblock javascript %}

CommodityTracker/templates/CommodityTracker/basecommodity_list.html
{% extends "base_template.html" %}
{% load widget_tweaks %}

{% block title %}
   {{block.super}}: Base Commodities List
{% endblock title %}


{% block content %}


  {% if basecommodity_list %}
  <table class="table table-striped mb-4">
    <thead class="thead-inverse">
      <tr>
        <th>Commodity</th>
      </tr>
    </thead>
    <tbody>
      {% for bc in basecommodity_list %}
        <tr>
          <td>
            <p class="mb-0">
              <a href="{% url 'base-commodity-detail' bc.pk %}">{{ bc.name }}</a>
            </p>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  {% else %}
      <p>There are no categories!</p>
    {% endif %}       

{% endblock content %}

{% block footer %}

{{block.super}}
{% endblock footer %}

CommodityTracker/templates/CommodityTracker/benchmark.html
{% extends "base_template.html" %}
{% load widget_tweaks %}

{% block title %}
   {{block.super}}: Categories List
{% endblock title %}




{% block content %}

    <div class="mb-4 text-right">
        <a href="{% url 'benchmark-commodity' 1 2 %}" class="btn btn-primary">Benchmark against internal purchase</a>
    </div>


    <h3>Title: {{ basecommodity }}</h3>

    <p><strong>commodity:</strong> {{ basecommodity }}</p> <!-- author detail link not yet defined -->


    <div class="card mb-2">
        <div class="card-body p-3">
          <div class="row mb-3">
            <div class="col-10">
                <H1>Historical Price Evolution</H1>
                <div style="height: 450px" id="chart_div_json"></div>
            </div>
            <div class="col-2 text-right">
              <small class="text-muted">some text</small>
            </div>
          </div>
        </div>
      </div>
  

      <div class="card mb-2">
          <div class="card-body p-3">
            <div class="row mb-3">
              <div class="col-10">
                  <H1>Price Table</H1>
                  <div id="table_div_json"></div>
              </div>
              <div class="col-2 text-right">
                <small class="text-muted">some text</small>
              </div>
            </div>
          </div>
        </div>
    


{% endblock %}


{% block footer %}
<h2> Category Footer </h2>
{{block.super}}
{% endblock footer %}


{% block javascript %} 
<script src="http://www.google.com/jsapi" type="text/javascript"></script>

<script>
        google.load("visualization", "1", {packages:["table", "line"]});
        google.setOnLoadCallback(drawTable);
        function drawTable() {

        var value_table = new google.visualization.Table(document.getElementById('table_div_json'));
        var table_data = new google.visualization.DataTable({{dataset|safe}});
        value_table.draw(table_data, {showRowNumber: true});


        var line_chart = new google.charts.Line(document.getElementById('chart_div_json'));
        var line_chart_data = new google.visualization.DataTable({{dataset|safe}});

        var options = {
            title: 'Purchase Benchmarking',
            curveType: 'function',
            legend: { position: 'bottom' }
            }

        line_chart.draw(line_chart_data, google.charts.Line.convertOptions(options));
        }
</script>
{% endblock javascript %}

CommodityTracker/templates/CommodityTracker/category_create.html
{% extends 'base_template.html' %}

{% block title %}Create a New Category{% endblock title %}



{% block content %}
  <form method="post" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success">Post</button>
  </form>
{% endblock %}

CommodityTracker/templates/CommodityTracker/category_detail.html
{% extends "base_template.html" %}

{% block content %}



<h3>Title: {{ category }}</h3>

  <p><strong>Category:</strong> {{ category }}</p> <!-- author detail link not yet defined -->
  <p><strong>Commodities:</strong> 

    Number of Commodities: {{ category.get_commodity_count }} 
    
<table class="table" >
        <thead class= "thead-inverse" >
        <tr>
          <th>Commodity Name</th>
          <th>Commodity id</th>
        </tr>
        </thead>
        
        <tbody>
           {% for base_commodity in category.basecommodities.all %} 
            <tr>
              <td><a href="{% url 'base-commodity-detail' base_commodity.pk %}">{{ base_commodity.name }}</a></td>
              <td class="align-middle"> {{base_commodity.id}} </td>
            </tr>
            {% endfor %}
        </tbody>
</table>

{% endblock %}

CommodityTracker/templates/CommodityTracker/category_form.html
{% extends "base_template.html" %}
{% load widget_tweaks %}

{% block title %}
   {{block.super}}: Categories 
{% endblock %}



{% block content %}
<form method="post" novalidate>
  {% csrf_token %}
  {% include 'includes/form.html' %}
  <button type="submit" class="btn btn-success">Submit</button>
</form>
{% endblock %}

{% block footer %}
Category Footer
{% endblock%}

CommodityTracker/templates/CommodityTracker/category_list.html
{% extends "base_template.html" %}
{% load widget_tweaks %}
{% block stylesheet %} 
<link rel="stylesheet" href="/static/css/style3.css">
{% endblock stylesheet%}
{% block title %}
   {{block.super}}: Categories
{% endblock title %}



{% block content %}




{% if category_list %}
<table class="table table-striped mb-4">
  <thead class="thead-inverse">
    <tr>
      <th>Category</th>
    </tr>
  </thead>
  <tbody>
    {% for cat in category_list %}
      <tr>
        <td>
          <p class="mb-0">
            <a href="{% url 'category-detail' cat.pk %}">{{ cat.name }}</a>
          </p>
          <small class="text-muted" > <a href="#" data-toggle="popover" data-trigger="focus" title="Description" data-content=" {{ cat.description }} ">See Description</a></small>                  
        </td>

        <td> 
          {% for commodity in cat.basecommodities.all %}
          <div>
              <p class="mb-0"> 
                  <a href="{% url 'base-commodity-detail' commodity.pk %}"> {{commodity.name}} </a>

              </p>
              <small class="text-muted"> <a href="#" data-toggle="popover" data-trigger="focus" title="Description" data-content=" {{ commodity.description }} ">See Description</a></small>                     
          </div>
          {% endfor %}
        </td>
    <td>KPIs</td>
  </tr>
    {% endfor %}
  </tbody>
</table>

{% else %}
    <p>There are no categories!</p>
  {% endif %}       
 

{% endblock content %}












{% block footer %}

{{block.super}}

{% endblock footer %}

CommodityTracker/templates/CommodityTracker/commodity_list.html
{% extends "base_template.html" %}
{% load widget_tweaks %}

{% block title %}
   {{block.super}}: Categories List
{% endblock title %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'bakery-portal-index' %}">Home</a></li>
<li class="breadcrumb-item active">Category</li>
<li class="breadcrumb-item"><a href="#">Commodities</a></li>
{% endblock breadcrumb %}

{% block content %}

  <div class="mb-4">
    <a href="{% url 'new-category' %}" class="btn btn-primary">New Category</a>
  </div>

  {% if category_list %}
  <table class="table table-striped mb-4">
    <thead class="thead-inverse">
      <tr>
        <th>Category</th>
        <th>Commodity</th>
        <th>Description</th>
        <th>API Sources</th>
      </tr>
    </thead>
    <tbody>
      {% for category in category_list %}
      {% url 'category-detail' category.pk as category_url %}
        <tr>
          <td>
            <p class="mb-0">
              <a href="#">{{ category.name }}</a>
            </p>
          </td>
          <td>Commodity</td>
          <td>Description</td>
          <td>API Sources</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  {% else %}
      <p>There are no categories!</p>
    {% endif %}       

{% endblock content %}

{% block footer %}

{{block.super}}
{% endblock footer %}

CommodityTracker/templates/CommodityTracker/generic_form.html
{% extends "base_template.html" %}
{% load widget_tweaks %}
{% block stylesheet %} 
<link rel="stylesheet" href="/static/css/style3.css">
{% endblock stylesheet%}
{% block title %}
   {{block.super}}: Categories
{% endblock title %}



{% block content %}



<form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">Post</button>
</form>



{% endblock content %}












{% block footer %}

{{block.super}}

{% endblock footer %}

CommodityTracker/templates/CommodityTracker/purchasing_home.html
{% extends "base_template.html" %}
{% load widget_tweaks %}
{% block stylesheet %} 
<link rel="stylesheet" href="/static/css/style3.css">
{% endblock stylesheet%}
{% block title %}
   {{block.super}}: Categories
{% endblock title %}


{% block content %}

<div class="mb-4 text-right">
    <a href="{% url 'app-init' %} " class="btn btn-primary">Add Base Commodities</a>
</div>


<div class="w3-padding-32" >
    <h3>  CATEGORIES AND BASE COMMODITIES  </h3>
    <p>
        "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum 
        deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non 
        provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum 
        fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis 
        est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis 
        voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis 
        aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. 
        Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias 
        consequatur aut perferendis doloribus asperiores repellat."
    </p>
</div>
    
<div class="table-wrapper" >

  {% if category_list %}
  <table class="table  mb-4 table-hover">
    <thead class="thead-inverse">
      <tr>
        <th>Categories</th>
        <th>Base Commodities</th>
        <th>KPIs</th>
    </tr>
    </thead>
    <tbody>
      {% for cat in category_list %}
        <tr>
          <td class="w3-hover-shadow" >
            <p class="mb-0">
              <a href="{% url 'category-detail' cat.pk %}">{{ cat.name }}</a>
            </p>
            <small class="text-muted" > <a href="#" data-toggle="popover" data-trigger="focus" title="Description" data-content=" {{ cat.description }} ">See Description</a></small>                  
          </td>

          <td> 
            <div class="w3-third w3-margin-bottom">
                <ul class="w3-ul w3-center ">
                {% for commodity in cat.basecommodities.all %}
                    <li class="w3-padding-16 w3-hover-shadow">
                            <a href="{% url 'base-commodity-detail' commodity.pk %}"> {{commodity.name}} </a> <br>
                            <small class="text-muted"> <a href="#" data-toggle="popover" data-trigger="focus" title="Description" data-content=" {{ commodity.description }} ">See Description</a></small>                          
                    </li>
                {% endfor %}
                </ul>
            </div>
          </td>
      <td  >KPIs</td>
    </tr>
      {% endfor %}
    </tbody>
  </table>

  {% else %}
      <p>There are no categories!</p>
    {% endif %}       
</div>

<div class="mb-4 text-right">
    <a href="{% url 'purchase-commodity-add' %} " class="btn btn-primary">Add Purchase Commodities</a>
</div>
<div class="w3-padding-32" >
    <h3>  CATEGORIES AND PURCHASE COMMODITIES  </h3>
    <p>
        "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum 
        deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non 
        provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum 
        fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis 
        est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis 
        voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis 
        aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. 
        Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias 
        consequatur aut perferendis doloribus asperiores repellat."
    </p>
</div>

<div class="table-wrapper" >
    
      {% if purchasecommodity_list %}
      <table class="table table-hover mb-4">
        <thead class="thead-inverse">
          <tr>
            <th>Purchase Commodities</th>
            <th>Benchmark Commodities</th>
            <th>KPIs</th>
        </tr>
        </thead>
        <tbody>
          {% for pc in purchasecommodity_list %}
            <tr>
              <td class="w3-hover-shadow">
                <p class="mb-0">
                  <a href="{% url 'purchase-commodity-detail' pc.pk %}">{{ pc.name }}</a>
                </p>
                <small class="text-muted" > <a href="#" data-toggle="popover" data-trigger="focus" title="Description" data-content=" {{ pc.description }} ">See Description</a></small>                  
              </td>
    
              <td> 
                <div class="w3-third w3-margin-bottom">
                    <ul class="w3-ul w3-center ">
                       <li class="w3-padding-16 w3-hover-shadow">
                            <a href="{% url 'base-commodity-detail' pc.benchmark1.pk %}"> {{pc.benchmark1.name}} </a> <br>
                            <small class="text-muted"> <a href="#" data-toggle="popover" data-trigger="focus" title="Description" data-content=" {{ commodity.description }} ">See Description</a></small>                     
                        </li>
                        <li>
                            <a href="{% url 'base-commodity-detail' pc.benchmark2.pk %}"> {{pc.benchmark2.name}} </a> <br>
                            <small class="text-muted"> <a href="#" data-toggle="popover" data-trigger="focus" title="Description" data-content=" {{ commodity.description }} ">See Description</a></small>                     
                        </li>

                        <li>
                            <a href="{% url 'base-commodity-detail' pc.benchmark3.pk %}"> {{pc.benchmark3.name}} </a> <br>
                            <small class="text-muted"> <a href="#" data-toggle="popover" data-trigger="focus" title="Description" data-content=" {{ commodity.description }} ">See Description</a></small>                     
                        </li>
                    </ul>
                </div>
              </td>
          <td>KPIs</td>
        </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>There are no purchase commodities!</p>
    {% endif %}       
</div>
{% endblock content %}

{% block footer %}

{{block.super}}
{% endblock footer %}

{% block javascript %}
{{block.super}}

{% endblock javascript %}

CommodityTracker/templates/CommodityTracker/signup.html
{% extends 'base_template.html' %}

{% block javascript %}
<script>
  $("#id_username").change(function () {
    var form = $(this).closest("form");
    console.log($(this).val())
    $.ajax({
      url: form.attr('data-validate-username-url'),
      data: form.serialize(),
      dataType: 'json',
      success: function (data) {
        if (data.is_taken) {
          alert(data.error_message);
        }
      }
    });

  });
</script>
{% endblock %}


{% block content %}
  <form method="post" data-validate-username-url="{% url 'validate-username' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}