boards/urls.py
from django.conf.urls import include, url

from boards import views

urlpatterns = [
    url(r'^$', views.BoardListView.as_view(), name='boards-index'),
    url(r'^boards/(?P<pk>\d+)/$', views.TopicListView.as_view(), name='board_topics'),
    url(r'^boards/(?P<pk>\d+)/new/$', views.new_topic, name='new_topic'),    
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/$', views.PostListView.as_view(), name='topic_posts'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/reply/$', views.reply_topic, name='reply_topic'),
    url(r'^boards/new_post/$', views.NewPostView.as_view(), name='new_post'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/posts/(?P<post_pk>\d+)/edit/$',
    views.PostUpdateView.as_view(), name='edit_post'),
]

customeranalytics/urls.py
from django.conf.urls import include, url
from customeranalytics import views


urlpatterns = [
    url(r'^$', views.CustomerAnalyticsHome, name='customer-analytics-home'),
]

# Company Urls
urlpatterns += [
    url(r'^companies/$', views.CompanyListView.as_view(), name='companies'),
    url(r'company/(?P<pk>\d+)$', views.CompanyDetailView.as_view(), name='company-detail'),
]


# Branch Urls
urlpatterns += [
    url(r'branches/$', views.BranchListView.as_view(), name='branches'),
    url(r'branch/(?P<pk>\d+)$', views.BranchDetailView.as_view(), name='branch-detail'),
]


# Occassion Urls
urlpatterns += [
    url(r'occassions/$', views.OccassionListView.as_view(), name='occassions'),
    url(r'occassion/(?P<pk>\d+)$', views.OccassionDetailView.as_view(), name='occassion-detail'),
]

# Customer Urls
urlpatterns += [
    url(r'customers/$', views.customer_list, name='customers'),
    url(r'customer/(?P<pk>\d+)$', views.CustomerDetailView.as_view(), name='customer-detail'),
    url(r'customer/update/$', views.update_customers, name='customer-update'),
]

# Order Urls
urlpatterns += [
    url(r'^orders/$', views.OrderListView.as_view(), name='orders'),
    url(r'order/(?P<pk>\d+)$', views.OrderDetailView.as_view(), name='order-detail'),
]


# Form Handling
urlpatterns += [   
    url(r'^data/$', views.data_upload, name='data-upload'),
]

urlpatterns += [  
    url(r'^profile/create/$', views.update_profile, name='profile_create'),
]

yamaki - Backup 06Jan2018/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView

from idealytix import views as idealytix_views
from CommodityTracker import views as commodity_views
from boards import views as boards_views

#URL pattern mappings

urlpatterns = [
    url(r'^$', idealytix_views.home, name='home'),
]

urlpatterns += [
    url(r'^commodity/', include('CommodityTracker.urls')),
    url(r'^forums/', include('boards.urls')),    
    url(r'^accounts/', include('accounts.urls')),    
    url(r'^bakery/', include('idealytix.urls')),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += [
    url(r'^admin/', admin.site.urls),
]

yamaki/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView

from idealytix import views as idealytix_views
from accounts import views as accounts_views
from salesanalytics import views as salesanalytics_views
from webanalytics import views as webanalytics_views
from customeranalytics import views as customeranalytics_views
from inventoryanalytics import views as inventoryanalytics_views
from accountsanalytics import views as accountsanalytics_views
from CommodityTracker import views as purchaseanalytics_views
from boards import views as boards_views
from hranalytics import views as hr_views

#URL pattern mappings

urlpatterns = [
    url(r'^$', idealytix_views.home, name='home'),
]

urlpatterns += [
    url(r'^bakery/', include('idealytix.urls')),
    url(r'^sales/', include('salesanalytics.urls')),
    url(r'^web/', include('webanalytics.urls')),
    url(r'^customer/', include('customeranalytics.urls')),
    url(r'^inventory/', include('inventoryanalytics.urls')),
    url(r'^commodity/', include('CommodityTracker.urls')),
    url(r'^sales/', include('accountsanalytics.urls')),
    url(r'^hr/', include('hranalytics.urls')),
    url(r'^accounts/', include('accounts.urls')),    
    url(r'^forums/', include('boards.urls')),    
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += [
    url(r'^admin/', admin.site.urls),
]

customeranalytics/models.py
from django.db import models
from django.urls import reverse #Used to generate URLs by reversing the URL patterns
import uuid # Required for unique book instances
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import date

# Create your models here.


class Company(models.Model):
    company_name = models.CharField(max_length=50)

    def __str__(self):
        return '%s' % (self.company_name)

    def get_absolute_url(self):
        return reverse('company-detail', args=[str(self.id)])
    

class Branch(models.Model):
    branch_name = models.CharField(max_length=50)
    company_name = models.ForeignKey(Company, blank=True, null=True, on_delete=models.SET_NULL)
    
    def __str__(self):
        return '%s' % (self.branch_name)

    def get_absolute_url(self):
        return reverse('branch-detail', args=[str(self.id)])

    def get_orders_sorted_by_date(self):
        return self.orders.order_by('Order_Date').reverse()


class Customer(models.Model):
    phone_number = models.IntegerField(null=True)
    customer_name = models.CharField(max_length = 100, blank=True)

    def __str__(self):
        return '%s' % (self.customer_name)

    def get_absolute_url(self):
        return reverse('customer-detail', args=[str(self.id)])

    def get_order_count(self):
        return self.orders.count()
    
    def get_latest_order(self):
        latest_order = self.orders.latest('Order_Date')
        return latest_order

    def get_absolute_url(self):
        return reverse('customer-detail', args=[str(self.id)])  

    def get_orders_sorted_by_date(self):
        return self.orders.order_by('Order_Date').reverse()


class Occassion(models.Model):
    occassion_name = models.CharField(max_length=100, blank=True)
    
    def __str__(self):
        return '%s' % (self.occassion_name)

    def get_absolute_url(self):
        return reverse('occassion-detail', args=[str(self.id)])

    def get_orders_sorted_by_date(self):
        return self.orders.order_by('Order_Date').reverse()


class Order(models.Model):
    Company = models.ForeignKey(Company, blank=True, null=True, on_delete=models.SET_NULL, related_name='orders')
    Branch = models.ForeignKey(Branch, blank=True, null=True, on_delete=models.SET_NULL, related_name='orders')
    Customer = models.ForeignKey(Customer, blank=True, null=True, on_delete=models.SET_NULL, related_name='orders')
    Occassion = models.ForeignKey(Occassion, blank=True, null=True, on_delete=models.SET_NULL, related_name='orders')
    Order_Date = models.DateField( blank=True, null=True)
    Order_No = models.IntegerField(null=True, blank=True)
    Total_Amount = models.FloatField(null=True, blank=True)

    def __str__(self):
        return 'for %s on %s' % (self.Total_Amount, self.Order_Date)

    def get_absolute_url(self):
        return reverse('order-detail', args=[str(self.id)])

    def create_order(self, i, company_name):
        print('order received')
        print (i)
        self.Company, c0 = Company.objects.get_or_create(company_name = company_name)
        self.Order_No = i['Order_No']
        self.Order_Date = i['Order_Date']
        self.Total_Amount = i['Total_Amount']
        self.Customer, c1 = Customer.objects.get_or_create(
                            phone_number = i['Contact_No'],
                            customer_name = i['Customer_Name']
                            )
        self.Occassion, c2 = Occassion.objects.get_or_create(occassion_name = i['Occassion'])
        self.Branch, c3 = Branch.objects.get_or_create(branch_name = i['Branch'], company_name = self.Company )

        self.save()




class Document(models.Model):
    name = models.CharField(max_length=50)
    file = models.FileField(upload_to='files/%Y')




# CREATE USER PROFILE
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company_name = models.ForeignKey(Company, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return '%s' % (self.user)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

customeranalytics/forms.py
from django import forms
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
import datetime #for checking renewal date range.
from .models import Company, Customer, Branch, Order, Occassion, Document


class DocumentForm(ModelForm):
    class Meta:
        model = Document
        fields = '__all__'


# USER AND PROFILE FORMS
from .models import Profile
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('user', 'company_name')

# SEARCH FORMS

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = 'Company', 'Branch', 'Occassion'

customeranalytics/templates/celebration/branch_detail.html
{% extends "base_template.html" %}

{% block content %}
  <h3>Title: {{ branch }}</h3>

  <p><strong>Branch:</strong> {{ branch }}</p> <!-- author detail link not yet defined -->
  <p><strong>Orders:</strong> 

    <table class="w3-table">
        <thead>
            <th>Customer Name</th>
            <th>Order Date</th>
            <th>Order Amount</th>
        </thead>

        <tbody>
            {% for order in branch.get_orders_sorted_by_date %}
            <tr>
                <td><a href="{{order.Customer.get_absolute_url}}"> {{ order.Customer }} </a></td>
                <td><a href="{{order.get_absolute_url}}">{{ order.Order_Date }}</a></td>
                <td><a href="{{order.get_absolute_url}}">{{ order.Total_Amount }}</a></td>
            </tr> 
            {% empty %}
            {% endfor %}                
        </tbody>
    </table>


{% endblock %}

customeranalytics/templates/celebration/branch_list.html
{% extends "base_template.html" %}

{% block content %}

<h3>Branch List</h3>

<div class="w3-row-padding w3-margin-bottom">
  <div class="w3-panel">
        <div class="">
            <h5>Branch List</h5>
            <table class="w3-table-all w3-card-4 " >
              <thead>
                <th>Branch Name</th>
              </thead>

              {% for branch in branch_list %}
                <tr >
                    <td><a href="{{branch.get_absolute_url}}">{{ branch }}</a></td>  
                  </tr>
                {% empty %}
                <td>There are no branches!</td>
                {% endfor %}
            </table>
        </div>
      </div>
  </div>     




{% endblock %}

customeranalytics/templates/celebration/company_detail.html
{% extends "base_template.html" %}

{% block content %}
  <h3>Title: {{ company }}</h3>

  <p><strong>Company:</strong> {{ company }}</p> <!-- author detail link not yet defined -->
  <p><strong>Orders:</strong> 
    {% for order in company.order_set.all %} 
        <hr>
            <a href="{% url 'order-detail' order.id %}">{{ order.order_date }}</a> 

          
    {% endfor %}
    </p>  

{% endblock %}

customeranalytics/templates/celebration/company_form.html
{% extends "base_template.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

customeranalytics/templates/celebration/customer_detail.html
{% extends "base_template.html" %}

{% block content %}
  
<div class="w3-panel">
        <h3>{{ customer }}</h3>
        Number of Orders: {{ customer.orders.count }} 
        
</div>

    <table class="w3-table">
        <thead>
            <th>Order Date</th>
            <th>Order Amount</th>
            <th>Occassion</th>
            <th>Branch</th>
            <th>Company</th>
        </thead>

    <tbody>
    {% for order in customer.orders.all %} 
        <tr>
            <td><a href="{% url 'order-detail' order.id %}">{{ order.Order_Date }}</a></td>
            <td>{{order.Total_Amount}} </td>
            <td>{{order.Occassion}} </td>
            <td><a href="{% url 'branch-detail' order.Branch.id %}">{{order.Branch}}</a> </td>
            <td><a href="{% url 'company-detail' order.Company.id %}">{{order.Company}}</a> </td>
        </tr>
    {% empty %}        
        <p>There are no orders!</p>
    {% endfor %}
</tbody>
</table>

{% endblock %}

customeranalytics/templates/celebration/customer_list.html
{% extends "base_template.html" %}

{% block content %}

<h3>Customer List</h3>

<div class="w3-row-padding w3-margin-bottom">


  <div class="w3-panel">
                
        <div class="">
            <h5>Customer List</h5>
            <table class="w3-table-all w3-card-4 " >
              <thead>
                <th></th>
                <th>Customer Name</th>
                <th>Total Orders</th>
                <th>Last Order</th>
                <th>Contact Number</th>
                <th>Text Promotion</th>
              </thead>

              {% for customer in customer_list %}
              {% url 'order-detail' customer.get_latest_order.id as order_id %}
                <tr >
                    <td><i class="fa fa-user w3-text-blue w3-large"></i></td>
                    <td><a href="{{customer.get_absolute_url}}">{{ customer }}</a></td>  
                    <td>{{customer.get_order_count}}</td>
                    <td> <a href="{{order_id}}"> {{customer.get_latest_order}} </a> </td>
                    <td> Call: {{customer.phone_number}} </td>
                    <td> <button> Make Promotion </button> </td>  
                  </tr>
                {% empty %}
                <td>There are no customers!</td>
                {% endfor %}
            </table>



            <div class="pagination">
            <span class="step-links">
                {% if customer_list.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ customer_list.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ customer_list.number }} of {{ customer_list.paginator.num_pages }}.
                </span>

                {% if customer_list.has_next %}
                    <a href="?page={{ customer_list.next_page_number }}">next</a>
                    <a href="?page={{ customer_list.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
            </div>
        </div>


      </div>


    
      
  </div>     




{% endblock %}

customeranalytics/templates/celebration/file_upload.html
{% extends "base_template.html" %}
{% block content %}

    <form enctype="multipart/form-data" action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>


    {% if uploaded_file_url %}
        <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
    {% endif %}


{% endblock %}

customeranalytics/templates/celebration/index.html
{% extends "base_template.html" %}
{% load static %}

{% block content %}


<div class="w3-panel ">
    <div class="w3-quarter">
        <div class="w3-container w3-red w3-padding-16">
        <div class="w3-left"><i class="fa fa-shopping-bag w3-xxxlarge"></i></div>
        <div class="w3-right">
            <h3>{{ num_branch }}</h3>
        </div>
        <div class="w3-clear"></div>
        <a href=" {% url 'branches' %} ">  <h4>Branches</h4> </a>
        </div>
    </div>

    <div class="w3-quarter">
        <div class="w3-container w3-blue w3-padding-16">
        <div class="w3-left"><i class="fa fa-users w3-xxxlarge"></i></div>
        <div class="w3-right">
            <h3>{{ num_customers }}</h3>
        </div>
        <div class="w3-clear"></div>
        <a href="{% url 'customers' %}"> <h4>Customers</h4> </a>
        </div>
    </div>
    
    <div class="w3-quarter">
        <div class="w3-container w3-teal w3-padding-16">
        <div class="w3-left"><i class="fa fa-money w3-xxxlarge"></i></div>
        <div class="w3-right">
            <h3> {{ num_orders }} </h3>
        </div>
        <div class="w3-clear"></div>
        <a href="{% url 'orders' %}"> <h4>Orders</h4> </a>
        </div>
    </div>

    <div class="w3-quarter">
        <div class="w3-container w3-orange w3-text-white w3-padding-16">
        <div class="w3-left"><i class="fa fa-birthday-cake w3-xxxlarge"></i></div>
        <div class="w3-right">
            <h3> {{ num_occassions }} </h3>
        </div>
        <div class="w3-clear"></div>
        <a href="{% url 'occassions' %}"> <h4>Occassions</h4> </a>
        </div>
    </div>
</div>    

<div class="w3-panel">
  <div class="w3-row-padding" style="margin:0 -16px">
    <div class="w3-third">
      <h2> Celebration Home</h1>
        <div id="index_chart_div" ></div>
    </div>        
            
    <div class="w3-twothird">
        <h5>Highlights</h5>
        <table class="w3-table w3-striped w3-white">
          <tr>
            <td><i class="fa fa-user w3-text-blue w3-large"></i></td>
            <td>New record, over 90 views.</td>
            <td><i>10 mins</i></td>
          </tr>
          <tr>
            <td><i class="fa fa-bell w3-text-red w3-large"></i></td>
            <td>Database error.</td>
            <td><i>15 mins</i></td>
          </tr>
          <tr>
            <td><i class="fa fa-users w3-text-yellow w3-large"></i></td>
            <td>New record, over 40 users.</td>
            <td><i>17 mins</i></td>
          </tr>
          <tr>
            <td><i class="fa fa-comment w3-text-red w3-large"></i></td>
            <td>New comments.</td>
            <td><i>25 mins</i></td>
          </tr>
          <tr>
            <td><i class="fa fa-bookmark w3-text-blue w3-large"></i></td>
            <td>Check transactions.</td>
            <td><i>28 mins</i></td>
          </tr>
          <tr>
            <td><i class="fa fa-laptop w3-text-red w3-large"></i></td>
            <td>CPU overload.</td>
            <td><i>35 mins</i></td>
          </tr>
          <tr>
            <td><i class="fa fa-share-alt w3-text-green w3-large"></i></td>
            <td>New shares.</td>
            <td><i>39 mins</i></td>
          </tr>
        </table>
    </div>


    <hr>
    <div class="w3-container">
      <h5>General Stats</h5>
      <p>New Visitors</p>
      <div class="w3-grey">
        <div class="w3-container w3-center w3-padding w3-green" style="width:25%">+25%</div>
      </div>
  
      <p>New Users</p>
      <div class="w3-grey">
        <div class="w3-container w3-center w3-padding w3-orange" style="width:50%">50%</div>
      </div>
  
      <p>Bounce Rate</p>
      <div class="w3-grey">
        <div class="w3-container w3-center w3-padding w3-red" style="width:75%">75%</div>
      </div>
    </div>
    <hr>
  

    <div class="w3-container">
        <h5>Branches</h5>
        <table class="w3-table w3-striped w3-bordered w3-border w3-hoverable w3-white">
          <tr>
            <td>Karama</td>
            <td>65%</td>
          </tr>
          <tr>
            <td>Jumeirah</td>
            <td>15.7%</td>
          </tr>
          <tr>
            <td>Russia</td>
            <td>5.6%</td>
          </tr>
          <tr>
            <td>Spain</td>
            <td>2.1%</td>
          </tr>
          <tr>
            <td>India</td>
            <td>1.9%</td>
          </tr>
          <tr>
            <td>France</td>
            <td>1.5%</td>
          </tr>
        </table><br>
        <button class="w3-button w3-dark-grey">More Branches &nbsp;<i class="fa fa-arrow-right"></i></button>
      </div>
      <hr>
    
      <div class="w3-container">
          <h5>Recent Orders</h5>
          <ul class="w3-ul w3-card-4 w3-white">
            <li class="w3-padding-16">
              <img src="{% static "celebration/avatar2.png" %}" class="w3-left w3-circle w3-margin-right" style="width:35px">
              <span class="w3-xlarge">Mike</span><br>
            </li>
            <li class="w3-padding-16">
              <img src="{% static "celebration/avatar2.png" %}" class="w3-left w3-circle w3-margin-right" style="width:35px">
              <span class="w3-xlarge">Jill</span><br>
            </li>
            <li class="w3-padding-16">
              <img src="{% static "celebration/avatar2.png" %}" class="w3-left w3-circle w3-margin-right" style="width:35px">
              <span class="w3-xlarge">Jane</span><br>
            </li>
          </ul>
        </div>
        <hr>
      


  </div>   
</div>      

{% endblock %}

customeranalytics/templates/celebration/occassion_detail.html
{% extends "base_template.html" %}

{% block content %}

<div class="w3-panel">
    <h3>Title: {{ occassion }}</h3>
</div>

<div class="w3-panel">
    <p><strong>Occassion:</strong> {{ occassion }}</p>
    <p><strong>Orders:</strong> 
</div>

<div>
    <table class="w3-table">
        <thead>
            <th>Company</th>
            <th>Branch</th>
            <th>Order Date</th>
            <th>Customer Name</th>
            <th>Total Amount</th>
        </thead>
        <tbody>
            {% for order in occassion.get_orders_sorted_by_date %} 
                <tr>
                <td><a href="{{order.Company.get_absolute_url}} "> {{ order.Company}} </a> </td>
                <td><a href="{{order.Branch.get_absolute_url}} "> {{ order.Branch}} </a> </td>
                <td><a href="{{order.Order_Date.get_absolute_url}} "> {{ order.Order_Date}}</a></td>
                <td><a href="{{order.Customer.get_absolute_url}} "> {{ order.Customer }}</a></td>
                <td>{{ order.Total_Amount }}</td>
            </tr>
            {% empty%}
                <p>There are no orders!</p>
            {% endfor %}
        </tbody>
    </table>
    
</div>

{% endblock %}

customeranalytics/templates/celebration/occassion_list.html
{% extends "base_template.html" %}

{% block content %}
    <h3>Occassion List</h3>

    {% if occassion_list %}
    <ul class="w3-ul w3-card-4 w3-hoverable">
      {% for occassion in occassion_list %}
      <li>
        <a href="{{occassion.get_absolute_url}}">{{ occassion }}</a> 
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no occassion!</p>
    {% endif %}       
{% endblock %}

customeranalytics/templates/celebration/order_detail.html
{% extends "base_template.html" %}

{% block content %}
  <h3>Title: {{ order }}</h3>

  <p><strong>Branch:</strong> <a href="{% url 'branch-detail' order.Branch.pk %}">{{ order.Branch.branch_name}}</a></p> 
  <p><strong>customer:</strong> <a href="{% url 'customer-detail' order.Customer.pk %}">{{ order.Customer.customer_name}}</a></p> 
  <p><strong>Occassion:</strong> {{ order.Occassion }}</p> 
  <p><strong>Order Date:</strong> {{ order.Order_Date }}</p> 
  <p><strong>Order No:</strong> {{ order.Order_No }}</p> 
  <p><strong>Total Amount:</strong> {{ order.Total_Amount }}</p> 
  <p><strong>Delivery Time:</strong> {{ order.Delivery_Time }}</p> 
  <p><strong>Delivery Mode:</strong> {{ order.Delivery_Mode }}</p> 
  
{% endblock %}

customeranalytics/templates/celebration/order_list.html
{% extends "base_template.html" %}

{% block content %}
<div class="w3-panel">

  <h3>Order List</h3>
  <a href="{% url 'data-upload' %}"> <button class="w3-btn w3-wide w3-red w3-right" > Upload Orders </button> </a>

</div>

<div class="w3-panel">

  <table class="w3-table-all w3-card-4 ">
    <thead>
      <th> Company </th>
      <th> Branch </th>
      <th> Customer </th>
      <th> Last Order Delivery Date </th>
      <th> Order Amount </th>
    </thead>
      <tbody>
            {% for order in order_list %}
        <tr>
            <td><a href=" {{order.Company.get_absolute_url}}"> {{order.Company}}</a> </td>
            <td><a href=" {{order.Branch.get_absolute_url}}"> {{order.Branch}}</a> </td>
            <td> <a href=" {{order.Customer.get_absolute_url}}"> {{order.Customer}} </a> </td>
            <td>{{order.Order_Date}}</td>
            <td>{{order.Total_Amount}}</td>
        </tr>
            {% empty %}
              <p>There are no orders to display!</p>
            {% endfor %}
      </tbody>
    </table>
  

</div>
{% endblock %}

customeranalytics/templates/celebration/profile.html
<form method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <button type="submit">Save changes</button>
  </form>

customeranalytics/templates/celebration/profile_form.html
{% extends "base_template.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ user_form.as_table }}
    {{ profile_form.as_table }}    
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}